### ISSUE TITLE
Program cannot be downloaded

### ISSUE THREAD

**Issue by orjanv** [odinuge/nrk-tv-downloader#44]
I have tried a program: https://tv.nrksuper.no/program/MSUI14009011/plass-bakpaa-kosten, which is still available and can be played at the website, but get this error:

parse error: Invalid numeric literal at line 1, column 4
parse error: Invalid numeric literal at line 1, column 4
Available episodes in "": 0

The program is not available through https://tv.nrk.no/program/MSUI14009011/plass-bakpaa-kosten wither:

parse error: Invalid numeric literal at line 1, column 10
parse error: Invalid numeric literal at line 1, column 10
Program ""
 - Tv program is not available: 

Tried with the dryrun only too.

**Comment by shazzr** [comment]
Same issue here.

./nrk-tv-downloader.sh https://tv.nrk.no/program/MSUI14009516/roeverrotta
parse error: Invalid numeric literal at line 1, column 10
parse error: Invalid numeric literal at line 1, column 10
Program ""
 - Tv program is not available:

**Comment by smagnusson** [comment]
I am finding sometimes the script is not removing quote ("") marks from the URLs. I believe the fix will be for the script to remove any quote marks from the download URLs.

**Comment by orjanv** [comment]
> I am finding sometimes the script is not removing quote ("") marks from the URLs. I believe the fix will be for the script to remove any quote marks from the download URLs.

What do you mean? Do you have a fix?

**Comment by smagnusson** [comment]
I will have a look at the URLs above that you and others have issues with. I have only had a problem with one URL so I might not be experiencing the same problem. I do not have a fix, I have only provided assistance on identifying the source of the problem.

When I run:

./nrk-tv-downloader.sh https://tv.nrk.no/serie/dagsrevyen-21/202007/NNFA27073120/avspiller

I debugged the code to see where it is failing and this is when it attempts to perform the following and fails because the request results in a 404 not found HTTP result:

ffmpeg -i http://nordond5a-f.akamaihd.net/i/wo/open/ps/nn/nnfa27073120/nnfa27073120ah/nnfa27073120ah_,205,380,632,1394,2410,.mp4.csmil/"index_4_av.m3u8?e=82d461566017da20&"  -c copy -bsf:a aac_adtstoasc -stats -loglevel info -y ./NRK_nyheter_31.07.2020.mp4

If you remove the quote mark and final ampersand then the above command will proceed, i.e.

ffmpeg -i http://nordond5a-f.akamaihd.net/i/wo/open/ps/nn/nnfa27073120/nnfa27073120ah/nnfa27073120ah_,205,380,632,1394,2410,.mp4.csmil/index_4_av.m3u8?e=82d461566017da20&  -c copy -bsf:a aac_adtstoasc -stats -loglevel info -y ./NRK_nyheter_31.07.2020.mp4

**Comment by smagnusson** [comment]
@orjanv and @shazzr your issue was different to mine but I made a simple fix you can manually add. On these programmes the HTML format is different to what the script expects. Open the script and in the location shown by the screen shot add this text:

	if [ -z "$program_id" ]; then
		local program_id=$(echo "$html" | sed -n "s/^.*nrk:program-id\" content=\"\([^\"]*\).*$/\1/p")
	fi

<img width="1087" alt="Screen Shot 2020-08-18 at 9 06 01 PM" src="https://user-images.githubusercontent.com/1609886/90494130-46a8cb80-e197-11ea-8fe7-b7711b747eef.png">


Does that work? I have successfully downloaded  https://tv.nrk.no/program/MSUI14009011/plass-bakpaa-kosten and https://tv.nrk.no/program/MSUI14009516/roeverrotta with this fix. 

I also fixed my issue that broke https://tv.nrk.no/serie/dagsrevyen-21/202007/NNFA27073120/avspiller
To fix that I changed the function getBestStream from
echo "${master//master.m3u8/"$new_stream"}"
to 
echo "${master//master.m3u8/$new_stream}"
(i.e. remove two quotes).

Let me know how you get on.

**Comment by orjanv** [comment]
Thanks @smagnusson, the first if-test did help on the "plass bak på kosten" show, thanks for that. 
I noticed a different issue just now, try downloading the series https://tv.nrk.no/serie/ronja-roeverdatter/ and see if that works for you. Your fix didn't solve that one, not with the second fix either. 

![Screenshot_20200818_164429](https://user-images.githubusercontent.com/574268/90528050-7c878900-e172-11ea-8504-31147809ecae.png)

**Comment by orjanv** [comment]
I tried a few different URLs too, and it it gives nothing on the nrksuper.no domain compared to "found no seasons" on the tv.nrk.no domain:

![Screenshot_20200818_165016](https://user-images.githubusercontent.com/574268/90528561-0df6fb00-e173-11ea-9f95-feed977616fb.png)

**Comment by odinuge** [comment]
Should hopefully be fixed by #48 

Season and all-episodes downloading is still broken tho.
